// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/hyperledger/fabric/plugins/gscc/protos/gscc.proto

package protos // import "github.com/hyperledger/fabric/plugins/gscc/protos"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryResultBytes struct {
	ResultBytes          []byte   `protobuf:"bytes,1,opt,name=resultBytes,proto3" json:"resultBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResultBytes) Reset()         { *m = QueryResultBytes{} }
func (m *QueryResultBytes) String() string { return proto.CompactTextString(m) }
func (*QueryResultBytes) ProtoMessage()    {}
func (*QueryResultBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_004cbdc3a35445b2, []int{0}
}
func (m *QueryResultBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResultBytes.Unmarshal(m, b)
}
func (m *QueryResultBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResultBytes.Marshal(b, m, deterministic)
}
func (dst *QueryResultBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResultBytes.Merge(dst, src)
}
func (m *QueryResultBytes) XXX_Size() int {
	return xxx_messageInfo_QueryResultBytes.Size(m)
}
func (m *QueryResultBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResultBytes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResultBytes proto.InternalMessageInfo

func (m *QueryResultBytes) GetResultBytes() []byte {
	if m != nil {
		return m.ResultBytes
	}
	return nil
}

type QueryResponse struct {
	Results              []*QueryResultBytes `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore              bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Id                   string              `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	TxId                 string              `protobuf:"bytes,4,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_004cbdc3a35445b2, []int{1}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (dst *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(dst, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResults() []*QueryResultBytes {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *QueryResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryResultBytes)(nil), "protos.QueryResultBytes")
	proto.RegisterType((*QueryResponse)(nil), "protos.QueryResponse")
}

func init() {
	proto.RegisterFile("github.com/hyperledger/fabric/plugins/gscc/protos/gscc.proto", fileDescriptor_004cbdc3a35445b2)
}

var fileDescriptor_004cbdc3a35445b2 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xb4, 0xd0, 0xe2, 0x02, 0x42, 0x66, 0x31, 0x5b, 0xd4, 0x29, 0x62, 0xb0, 0x45,
	0x61, 0x64, 0xea, 0xc6, 0xc0, 0x80, 0x47, 0x96, 0x28, 0x89, 0x0f, 0xc7, 0x52, 0x5a, 0x47, 0x77,
	0x8e, 0xd4, 0xcc, 0xfc, 0x71, 0x44, 0x4d, 0xd5, 0x8a, 0xad, 0xdb, 0xbb, 0xa7, 0x77, 0x77, 0xfa,
	0x1e, 0x7f, 0x75, 0x3e, 0xb6, 0x43, 0xad, 0x9a, 0xb0, 0xd1, 0xed, 0xd8, 0x03, 0x76, 0x60, 0x1d,
	0xa0, 0xfe, 0xaa, 0x6a, 0xf4, 0x8d, 0xee, 0xbb, 0xc1, 0xf9, 0x2d, 0x69, 0x47, 0x4d, 0xa3, 0x7b,
	0x0c, 0x31, 0x24, 0xad, 0xf6, 0x5a, 0x5c, 0x26, 0x6b, 0xf9, 0xc2, 0xef, 0x3e, 0x06, 0xc0, 0xd1,
	0x00, 0x0d, 0x5d, 0x5c, 0x8f, 0x11, 0x48, 0xe4, 0x7c, 0x81, 0xc7, 0x51, 0xb2, 0x9c, 0x15, 0xd7,
	0xe6, 0xd4, 0x5a, 0x7e, 0x33, 0x7e, 0x73, 0x58, 0xeb, 0xc3, 0x96, 0x40, 0xac, 0xf8, 0x2c, 0x05,
	0x7e, 0xf3, 0x93, 0x62, 0xb1, 0x92, 0xe9, 0x11, 0xa9, 0xff, 0xe7, 0xcd, 0x21, 0x28, 0x1e, 0xf8,
	0xbc, 0xad, 0xa8, 0xdc, 0x04, 0x04, 0x99, 0xe5, 0xac, 0x98, 0x9b, 0x59, 0x5b, 0xd1, 0x7b, 0x40,
	0x10, 0xb7, 0x3c, 0xf3, 0x56, 0x4e, 0x72, 0x56, 0x5c, 0x99, 0xcc, 0x5b, 0x71, 0xcf, 0x2f, 0xe2,
	0xae, 0xf4, 0x56, 0x4e, 0xf7, 0xd6, 0x34, 0xee, 0xde, 0xec, 0xba, 0xe4, 0x8f, 0x01, 0x9d, 0x3a,
	0x81, 0x57, 0x09, 0x5e, 0xfd, 0xc1, 0xab, 0x23, 0x30, 0x7d, 0x3e, 0x9d, 0xdd, 0x57, 0x9d, 0x4a,
	0x7a, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x82, 0xd6, 0x76, 0xe1, 0x6b, 0x01, 0x00, 0x00,
}
